'use strict'

// Spike: generate a Claude marketplace from authored plugin-config.json files.
//
// Authoring layout (input):
//   <authoring>/marketplace.json                 -- {name, owner, metadata}
//   <authoring>/plugins/<dir>/plugin-config.json -- plugin.json fields + optional `dependencies`
//   <authoring>/plugins/<dir>/...                -- any other plugin content, copied verbatim
//
// A dependency is {"plugin": "<name>"} for the own marketplace, plus optional
// {"marketplace": "<name>", "source": "<marketplace add source>"} for an external one.
// For each plugin with dependencies the generator emits scripts/ensure-deps.sh and merges a
// SessionStart entry into hooks/hooks.json (authored hook entries are preserved).

const fs = require('node:fs')
const path = require('node:path')

function readJson(file) {
  return JSON.parse(fs.readFileSync(file, 'utf-8'))
}

// One shell-safe line per dependency: plugin|marketplace|source ('' marketplace = own).
function depLines(dependencies) {
  return dependencies
    .map((d) => {
      for (const key of ['plugin', 'marketplace', 'source']) {
        if (d[key] !== undefined && /[|\n']/.test(String(d[key]))) {
          throw new Error(`dependency field '${key}' must not contain | or quotes: ${d[key]}`)
        }
      }
      return `${d.plugin}|${d.marketplace ?? ''}|${d.source ?? ''}`
    })
    .join('\n')
}

function ensureDepsScript(ownMarketplace, dependencies) {
  return `#!/usr/bin/env bash
# GENERATED by src/generate.js -- do not edit. Ensures declared plugin dependencies are installed.
set -uo pipefail
own_mp='${ownMarketplace}'
log="\${POC_MARKER_DIR:-/tmp}/ensure-deps.log"
while IFS='|' read -r dep mp src; do
  [ -z "$dep" ] && continue
  mp="\${mp:-$own_mp}"
  if claude plugin list --json 2>/dev/null | grep -q "\\"id\\": \\"\${dep}@\${mp}\\""; then
    echo "dep=\${dep}@\${mp} status=present" >> "$log"
    continue
  fi
  if [ -n "$src" ] && ! claude plugin marketplace list --json 2>/dev/null | grep -q "\\"name\\": \\"\${mp}\\""; then
    if claude plugin marketplace add "$src" >/dev/null 2>&1; then
      echo "marketplace=\${mp} added_from=\${src}" >> "$log"
    else
      echo "marketplace=\${mp} ADD_FAILED src=\${src}" >> "$log"
      continue
    fi
  fi
  if claude plugin install "\${dep}@\${mp}" >/dev/null 2>&1; then
    echo "dep=\${dep}@\${mp} status=installed" >> "$log"
  else
    echo "dep=\${dep}@\${mp} status=INSTALL_FAILED" >> "$log"
  fi
done <<'DEPS'
${depLines(dependencies)}
DEPS
exit 0
`
}

// Append the generated SessionStart entry to hooks/hooks.json, keeping authored entries.
function mergeHook(pluginOut) {
  const hooksFile = path.join(pluginOut, 'hooks', 'hooks.json')
  const data = fs.existsSync(hooksFile) ? readJson(hooksFile) : { hooks: {} }
  data.hooks.SessionStart ??= []
  data.hooks.SessionStart.push({
    hooks: [{ type: 'command', command: '${CLAUDE_PLUGIN_ROOT}/scripts/ensure-deps.sh' }],
  })
  fs.mkdirSync(path.dirname(hooksFile), { recursive: true })
  fs.writeFileSync(hooksFile, `${JSON.stringify(data, null, 2)}\n`)
}

function generate(authoringDir, outDir) {
  const marketplace = readJson(path.join(authoringDir, 'marketplace.json'))
  fs.rmSync(outDir, { recursive: true, force: true })

  const entries = []
  const pluginsDir = path.join(authoringDir, 'plugins')
  for (const dir of fs.readdirSync(pluginsDir).sort()) {
    const src = path.join(pluginsDir, dir)
    const out = path.join(outDir, 'plugins', dir)
    const config = readJson(path.join(src, 'plugin-config.json'))
    const { dependencies = [], ...manifest } = config

    fs.cpSync(src, out, { recursive: true, filter: (p) => path.basename(p) !== 'plugin-config.json' })
    fs.mkdirSync(path.join(out, '.claude-plugin'), { recursive: true })
    fs.writeFileSync(path.join(out, '.claude-plugin', 'plugin.json'), `${JSON.stringify(manifest, null, 2)}\n`)

    if (dependencies.length > 0) {
      fs.mkdirSync(path.join(out, 'scripts'), { recursive: true })
      const script = path.join(out, 'scripts', 'ensure-deps.sh')
      fs.writeFileSync(script, ensureDepsScript(marketplace.name, dependencies))
      fs.chmodSync(script, 0o755)
      mergeHook(out)
    }
    entries.push({ name: manifest.name, source: `./plugins/${dir}`, description: manifest.description, version: manifest.version })
  }

  fs.mkdirSync(path.join(outDir, '.claude-plugin'), { recursive: true })
  fs.writeFileSync(
    path.join(outDir, '.claude-plugin', 'marketplace.json'),
    `${JSON.stringify({ ...marketplace, plugins: entries }, null, 2)}\n`,
  )
  process.stderr.write(`generated ${entries.length} plugin(s) into ${outDir}\n`)
}

function main() {
  const [authoringDir, outDir] = process.argv.slice(2)
  if (!authoringDir || !outDir) {
    process.stderr.write('usage: node src/generate.js <authoringDir> <outDir>\n')
    process.exit(2)
  }
  generate(authoringDir, outDir)
}

if (require.main === module) main()

module.exports = { generate, ensureDepsScript, depLines }
